import solid from 'vite-plugin-solid';
import { defineConfig } from 'vitest/config';

/**
 * The conformance suites run separately from the unit tests: they depend on fixture files that
 * are gitignored and fetched on demand (`bun run conformance`), so including them in the default
 * `vitest run` would make a fresh clone fail for a reason unrelated to the code.
 *
 * **Two projects, because the two fixture layers demand opposite render modes.**
 *
 * - `conformance-ssr` — the static layer (`classnames.json`, `accessible-descriptions.json`) was
 *   generated by `renderToStaticMarkup` with *no effects run*. `renderToString` reproduces that
 *   exactly, and it requires components compiled with `generate: 'ssr'`.
 * - `conformance-dom` — the post-flush layer is the same 50 cases rendered uncontrolled with
 *   effects settled, which is client rendering: the default `dom` compilation, jsdom, `flush()`.
 *
 * One plugin instance cannot serve both, so the split is structural rather than cosmetic.
 *
 * `hydratable: false` on the ssr side is required: hydration keys land as *attributes* and would
 * break the byte-identical `class` comparison.
 *
 * ⚠️ `ssr: true` on the ssr project is **not** redundant with `solid: { generate: 'ssr' }`, and
 * removing it breaks the suite outright. `vite-plugin-solid@3` injects a `browser` condition in
 * test mode (`isTestMode && !options.ssr`), and `@solidjs/web`'s exports map lists `browser`
 * *before* `node`, so the browser build wins and its `renderToString` is a stub that logs
 * "renderToString is not supported in the browser" and returns `undefined`. `ssr: true`
 * suppresses that injection — and it also stops the plugin forcing `environment: 'jsdom'`.
 * `options.solid` is merged last, so the explicit `generate`/`hydratable` still win over the
 * `hydratable: true` that `ssr: true` would otherwise imply.
 *
 * Neither project sets `resolve.conditions`. `vite-plugin-solid@3` supplies them per environment,
 * and hand-maintaining a list on top of that only *removes* entries.
 */
export default defineConfig({
  test: {
    projects: [
      {
        plugins: [solid({ ssr: true, solid: { generate: 'ssr', hydratable: false } })],
        test: {
          name: 'conformance-ssr',
          // `node`, not `jsdom`: a server render must not need a document, and running it
          // without one proves that. `extract.ts` constructs its own jsdom to parse the markup.
          environment: 'node',
          globals: true,
          include: [
            'test/conformance/classnames.test.ts',
            'test/conformance/accessible-descriptions.test.ts',
          ],
        },
      },
      {
        plugins: [solid()],
        test: {
          name: 'conformance-dom',
          environment: 'jsdom',
          globals: true,
          include: [
            'test/conformance/classnames-post-flush.test.ts',
            'test/conformance/actions.test.ts',
            'test/conformance/actions.solid.test.ts',
            'test/conformance/format.test.ts',
          ],
          setupFiles: ['./vitest-setup.ts'],
        },
      },
    ],
  },
});
